title: Test Static Site
author:
  name: Tierney Steelberg
  email: your-email@domain.com
description: >
  Test static site built during ILiADS 2025 at BMC.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { icon: "github", title: "Minima Theme repository at GitHub", url: "https://github.com/jekyll/minima" }
    - { icon: "x-twitter", title: "Jekyll profile at X (formerly Twitter)", url: "https://x.com/jekyllrb" }
  show_excerpts: true
  skin: auto # Options: auto, classic, dark, solarized, solarized-light, solarized-dark

# Build settings
baseurl: /static-test
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]
